import type { Config } from 'tailwindcss';

const config: Config = {
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      fontFamily: {
        'ranade': ['Ranade', 'sans-serif'],
        'mono': ['IBM Plex Mono', 'monospace'],
        'fredoka': ['Fredoka', 'sans-serif'],
        'poppins': ['Poppins', 'sans-serif'],
        'cursive': ['Pacifico', 'cursive'],
        'caveat': ['Caveat', 'cursive'],
        'golden': ['Gluten', 'serif'],
        'adobe-casion': ['adobe-casion', 'serif'],
        'sreda': ['Sreda', 'sans-serif'],
        'baskerville': ['Libre Baskerville', 'serif'],
      },
      colors: {
        'neo': {
          'black': '#000000',
          'yellow': '#FFD700',
          'blue': '#0066FF',
          'red': '#FF0000',
          'green': '#00CC00',
          'white': '#FFFFFF',
        },
        'y2k': {
          'hotpink': '#FF1493',
          'deeppink': '#FF10F0',
          'cyan': '#00FFFF',
          'lime': '#00FF00',
          'purple': '#9D00FF',
          'black': '#0a0a0a',
          'dark': '#1a1a1a',
        },
      },
      fontSize: {
        'xs': ['12px', { lineHeight: '16px' }],
        'sm': ['14px', { lineHeight: '20px' }],
        'base': ['16px', { lineHeight: '24px' }],
        'lg': ['18px', { lineHeight: '28px' }],
        'xl': ['20px', { lineHeight: '28px' }],
        '2xl': ['24px', { lineHeight: '32px' }],
        '3xl': ['30px', { lineHeight: '36px' }],
        '4xl': ['36px', { lineHeight: '40px' }],
        '5xl': ['48px', { lineHeight: '48px' }],
        '6xl': ['60px', { lineHeight: '60px' }],
        '7xl': ['72px', { lineHeight: '72px' }],
      },
      spacing: {
        '0': '0px',
        '1': '4px',
        '2': '8px',
        '3': '12px',
        '4': '16px',
        '5': '20px',
        '6': '24px',
        '7': '28px',
        '8': '32px',
        '9': '36px',
        '10': '40px',
        '12': '48px',
        '16': '64px',
        '20': '80px',
        '24': '96px',
        '32': '128px',
        '40': '160px',
        '48': '192px',
        '56': '224px',
        '64': '256px',
      },
      borderWidth: {
        '0': '0',
        'DEFAULT': '1px',
        '2': '2px',
        '4': '4px',
        '6': '6px',
        '8': '8px',
      },
      borderRadius: {
        'none': '0',
      },
      boxShadow: {
        'neo': '0px 8px 0px -2px rgba(0, 0, 0, 0.8)',
        'neo-lg': '0px 16px 0px -4px rgba(0, 0, 0, 0.8)',
        'neo-xl': '0px 24px 0px -6px rgba(0, 0, 0, 0.8)',
        'neo-2xl': '0px 32px 0px -8px rgba(0, 0, 0, 0.8)',
        'neon-yellow': '0px 0px 16px rgba(255, 215, 0, 0.6), 0px 8px 0px -2px rgba(0, 0, 0, 0.8)',
        'neon-blue': '0px 0px 16px rgba(0, 102, 255, 0.6), 0px 8px 0px -2px rgba(0, 0, 0, 0.8)',
        'none': 'none',
      },
      inset: {
        '0': '0',
        '1': '4px',
        '2': '8px',
        '3': '12px',
        '4': '16px',
        '6': '24px',
        '8': '32px',
        'full': '100%',
      },
      animation: {
        'float': 'float 6s ease-in-out infinite',
        'pulse-slow': 'pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'drift': 'drift 20s linear infinite',
        'wiggle': 'wiggle 0.5s ease-in-out infinite',
        'glow': 'glow 2s ease-in-out infinite',
      },
      keyframes: {
        float: {
          '0%, 100%': { transform: 'translateY(0px)' },
          '50%': { transform: 'translateY(-20px)' },
        },
        drift: {
          '0%': { transform: 'translateX(0px)' },
          '50%': { transform: 'translateX(20px)' },
          '100%': { transform: 'translateX(0px)' },
        },
        wiggle: {
          '0%, 100%': { transform: 'rotate(-1deg)' },
          '50%': { transform: 'rotate(1deg)' },
        },
        glow: {
          '0%, 100%': { boxShadow: '0px 0px 16px rgba(255, 215, 0, 0.3)' },
          '50%': { boxShadow: '0px 0px 32px rgba(255, 215, 0, 0.6)' },
        },
      },
      transitionDuration: {
        '0': '0ms',
        '75': '75ms',
        '100': '100ms',
        '150': '150ms',
        '200': '200ms',
        '300': '300ms',
        '500': '500ms',
        '700': '700ms',
        '1000': '1000ms',
      },
    },
  },
  plugins: [],
};

export default config;
